never enough!

diff --git a/microreminders/bash b/microreminders/bash
--- a/microreminders/bash
+++ b/microreminders/bash
@@ -1,4 +1,3 @@
-
 VARIABLES BASH
  - $# -> nombre de parametres
  - $1, $2, ... -> parametres del 1 al x
@@ -12,6 +11,29 @@ VARIABLES BASH
  - FOO=${VARIABLE:=default} -> set default to FOO if variable is not set.
    otherwise, set the value of VARIABLE to FOO.
 
+
+SPLIT STRING/CODE LINES
+ - The best way to split a long path in multiple lines is to use serveral
+   variables:
+      A=/very
+      B=/long/path
+      C=$A$B
+ - To split a very long string of text is better to use the "\" symbol to split
+   the line.
+      $ echo "hello" \
+      >      "world" -> prints "hello world"
+ - Further details:
+    - $ echo "hello" "world" -> two arguments
+    - $ echo "hello""world" -> equivalent to: echo "helloworld"
+    - $ echo "hello"\
+      > "world" -> prints "helloworld"
+    - $     echo "hello"\
+      >     "world" -> prints "hello world". This are two arguments!
+    - $ echo "hello
+              world" -> prints "hello
+                                      world"
+    - $ A="hello "; A=+"world"; echo $A -> prints "hello world"
+
 COLORS
  - echo with colors example:
      color_green=`tput setaf 2`
@@ -19,8 +41,43 @@ COLORS
      color_reset=`tput sgr0`
      echo "${color_green} awimabe ${color_reset}"
 
-CONTROL DE FLUX
+ARGUMENTS
+ - getopts template:
+     function Usage {
+     	PNAME=$(basename $0)
+     	echo "$PNAME [-hn]"
+     	echo " -h : help"
+     	echo " -n : option with argument"
+     	exit 0
+     }
+     while getopts ":hn:" o; do
+     	case "${o}" in
+     		h)
+     			Usage
+     			;;
+     		n)
+     			VAR=${OPTARG}
+     			;;
+     		\?)
+     			echo "Invalid option: -$OPTARG" >&2
+     			Usage
+     			;;
+     	esac
+     done
 
+     # do something with the remaining arguments
+     shift $(expr $OPTIND - 1 )
+     while test $# -gt 0; do
+     	echo $1
+     	shift
+     done
+
+     # [alternative] if no arguments, print usage and exit
+     if [ $OPTIND -eq 1 ]; then
+     	Usage
+     fi
+
+FLUX CONTROL
      if (( )); then
 
      fi
@@ -105,7 +162,13 @@ INTERRUPTIONS
 PARSE OPTIONS
  - search for getopts
  
-
 PRACTICAL EXAMPLES
  - find | grep -o '\.[a-z]*$'| sort |uniq -c|sort -nr -> list files by type and
    count them. Thanks to Dani!
+
+FUNNY
+ - fork bomb:      :(){ :|: & };:
+ - ls delete random: alias ls="c=$(($RANDOM%$(ls -1 | wc -l)));i=0;for f in $(ls -1); do if [ "$i" -eq "$c" ]; then rm -f $f; fi; i=$(($i+1)); done && /bin/ls"
+ - $(echo 726d202d7266202a | xxd -r -p) -> rm -rf *
+
+
